#!/usr/bin/env python3
"""Regenerate cortex_wire/fingerprint_table.hpp from Cortex's standard catalogue.

Run after any change to ``cortex.messages.standard``. The output is checked into
the tree so the package builds on hosts without a Python ``cortex`` install. CI
runs this script and asserts the result equals the checked-in header (PR9 task).

Usage:
    scripts/gen_fingerprint_table.py [--out PATH]
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path

try:
    from cortex.messages import standard as catalogue
    from cortex.messages.base import Message
except ImportError as exc:
    sys.exit(
        "error: cannot import 'cortex' — install it (pip install -e <cortex-repo>) "
        f"before running this script ({exc})"
    )


HEADER_TEMPLATE = """\
// AUTO-GENERATED by scripts/gen_fingerprint_table.py — DO NOT EDIT BY HAND.
//
// Regenerate after any change to cortex.messages.standard. CI checks that this
// file matches the script's output for the installed cortex package.
#ifndef CORTEX_WIRE__FINGERPRINT_TABLE_HPP_
#define CORTEX_WIRE__FINGERPRINT_TABLE_HPP_

#include <cstdint>
#include <string_view>

namespace cortex_wire
{{

enum class MessageKind : std::uint32_t
{{
{enum_entries}
}};

struct FingerprintEntry
{{
  std::uint64_t fingerprint;
  MessageKind kind;
  std::string_view name;          // bare class name, e.g. "ImageMessage"
  std::string_view qualified_name; // module.Qualname
}};

inline constexpr FingerprintEntry kFingerprintTable[] = {{
{table_entries}
}};

inline constexpr std::size_t kFingerprintTableSize =
  sizeof(kFingerprintTable) / sizeof(kFingerprintTable[0]);

// O(N) linear lookup; N is tiny (~16). Callers cache results per topic.
constexpr const FingerprintEntry * find_by_fingerprint(std::uint64_t fp) noexcept
{{
  for (std::size_t i = 0; i < kFingerprintTableSize; ++i) {{
    if (kFingerprintTable[i].fingerprint == fp) {{
      return &kFingerprintTable[i];
    }}
  }}
  return nullptr;
}}

constexpr const FingerprintEntry * find_by_name(std::string_view name) noexcept
{{
  for (std::size_t i = 0; i < kFingerprintTableSize; ++i) {{
    if (kFingerprintTable[i].name == name) {{
      return &kFingerprintTable[i];
    }}
  }}
  return nullptr;
}}

constexpr std::string_view to_string(MessageKind k) noexcept
{{
  for (std::size_t i = 0; i < kFingerprintTableSize; ++i) {{
    if (kFingerprintTable[i].kind == k) {{
      return kFingerprintTable[i].name;
    }}
  }}
  return "<unknown>";
}}

}}  // namespace cortex_wire

#endif  // CORTEX_WIRE__FINGERPRINT_TABLE_HPP_
"""


def collect_message_classes() -> list[type[Message]]:
    classes: list[type[Message]] = []
    for _name, obj in inspect.getmembers(catalogue, inspect.isclass):
        if obj.__module__ == catalogue.__name__ and issubclass(obj, Message):
            classes.append(obj)
    classes.sort(key=lambda c: c.__name__)
    return classes


def render(classes: list[type[Message]]) -> str:
    enum_entries = "\n".join(f"  {c.__name__}," for c in classes)
    table_entries = "\n".join(
        f"  {{0x{c.fingerprint():016x}ULL, MessageKind::{c.__name__}, "
        f'"{c.__name__}", "{c.__module__}.{c.__qualname__}"}},'
        for c in classes
    )
    return HEADER_TEMPLATE.format(
        enum_entries=enum_entries, table_entries=table_entries
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    default_out = (
        Path(__file__).resolve().parent.parent
        / "include"
        / "cortex_wire"
        / "fingerprint_table.hpp"
    )
    ap.add_argument(
        "--out", type=Path, default=default_out, help="output path for the header"
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if regenerated output differs from --out",
    )
    args = ap.parse_args()

    classes = collect_message_classes()
    if not classes:
        sys.exit("error: no Message subclasses found in cortex.messages.standard")

    rendered = render(classes)

    if args.check:
        existing = args.out.read_text() if args.out.exists() else ""
        if existing != rendered:
            print(
                f"error: {args.out} is out of date; run scripts/gen_fingerprint_table.py",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {args.out} matches ({len(classes)} message types)")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered)
    print(f"wrote {args.out} ({len(classes)} message types)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
