// AUTO-GENERATED by scripts/gen_fingerprint_table.py — DO NOT EDIT BY HAND.
//
// Regenerate after any change to cortex.messages.standard. CI checks that this
// file matches the script's output for the installed cortex package.
#ifndef CORTEX_ROS2_BRIDGE__CORTEX_WIRE__FINGERPRINT_TABLE_HPP_
#define CORTEX_ROS2_BRIDGE__CORTEX_WIRE__FINGERPRINT_TABLE_HPP_

#include <cstdint>
#include <string_view>

namespace cortex_ros2_bridge::cortex_wire
{

enum class MessageKind : std::uint32_t
{
  ArrayMessage,
  BytesMessage,
  DictMessage,
  FloatMessage,
  HeaderMessage,
  ImageMessage,
  IntMessage,
  ListMessage,
  MultiArrayMessage,
  MultiTensorMessage,
  PointCloudMessage,
  PoseMessage,
  StringMessage,
  TensorMessage,
  TimestampMessage,
  TransformMessage,
};

struct FingerprintEntry
{
  std::uint64_t fingerprint;
  MessageKind kind;
  std::string_view name;          // bare class name, e.g. "ImageMessage"
  std::string_view qualified_name; // module.Qualname
};

inline constexpr FingerprintEntry kFingerprintTable[] = {
  {0xdc00d2e72bf078f8ULL, MessageKind::ArrayMessage, "ArrayMessage", "cortex.messages.standard.ArrayMessage"},
  {0x2ca9f5d943ea7496ULL, MessageKind::BytesMessage, "BytesMessage", "cortex.messages.standard.BytesMessage"},
  {0x8849dfb1d9d7aed1ULL, MessageKind::DictMessage, "DictMessage", "cortex.messages.standard.DictMessage"},
  {0x65e8ef72b6e0c906ULL, MessageKind::FloatMessage, "FloatMessage", "cortex.messages.standard.FloatMessage"},
  {0x7ffb169cc00af1ffULL, MessageKind::HeaderMessage, "HeaderMessage", "cortex.messages.standard.HeaderMessage"},
  {0xa51dd7f890942cadULL, MessageKind::ImageMessage, "ImageMessage", "cortex.messages.standard.ImageMessage"},
  {0xde80ce01966606c9ULL, MessageKind::IntMessage, "IntMessage", "cortex.messages.standard.IntMessage"},
  {0x40487e947d65fdb6ULL, MessageKind::ListMessage, "ListMessage", "cortex.messages.standard.ListMessage"},
  {0x13db93d55ff51604ULL, MessageKind::MultiArrayMessage, "MultiArrayMessage", "cortex.messages.standard.MultiArrayMessage"},
  {0x4335558df26bc27bULL, MessageKind::MultiTensorMessage, "MultiTensorMessage", "cortex.messages.standard.MultiTensorMessage"},
  {0xbef60c17034e979aULL, MessageKind::PointCloudMessage, "PointCloudMessage", "cortex.messages.standard.PointCloudMessage"},
  {0xa50e8b029e07992fULL, MessageKind::PoseMessage, "PoseMessage", "cortex.messages.standard.PoseMessage"},
  {0xacf8d6475271e065ULL, MessageKind::StringMessage, "StringMessage", "cortex.messages.standard.StringMessage"},
  {0x9732b31762a314ffULL, MessageKind::TensorMessage, "TensorMessage", "cortex.messages.standard.TensorMessage"},
  {0xf4484907f9c22ee1ULL, MessageKind::TimestampMessage, "TimestampMessage", "cortex.messages.standard.TimestampMessage"},
  {0x35057ece715054d7ULL, MessageKind::TransformMessage, "TransformMessage", "cortex.messages.standard.TransformMessage"},
};

inline constexpr std::size_t kFingerprintTableSize =
  sizeof(kFingerprintTable) / sizeof(kFingerprintTable[0]);

// O(N) linear lookup; N is tiny (~16). Callers cache results per topic.
constexpr const FingerprintEntry * find_by_fingerprint(std::uint64_t fp) noexcept
{
  for (std::size_t i = 0; i < kFingerprintTableSize; ++i) {
    if (kFingerprintTable[i].fingerprint == fp) {
      return &kFingerprintTable[i];
    }
  }
  return nullptr;
}

constexpr const FingerprintEntry * find_by_name(std::string_view name) noexcept
{
  for (std::size_t i = 0; i < kFingerprintTableSize; ++i) {
    if (kFingerprintTable[i].name == name) {
      return &kFingerprintTable[i];
    }
  }
  return nullptr;
}

constexpr std::string_view to_string(MessageKind k) noexcept
{
  for (std::size_t i = 0; i < kFingerprintTableSize; ++i) {
    if (kFingerprintTable[i].kind == k) {
      return kFingerprintTable[i].name;
    }
  }
  return "<unknown>";
}

}  // namespace cortex_ros2_bridge::cortex_wire

#endif  // CORTEX_ROS2_BRIDGE__CORTEX_WIRE__FINGERPRINT_TABLE_HPP_
